spring.application.name=fitness-app

## Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.schemas=fitness_app
spring.jpa.properties.hibernate.default_schema=fitness_app
spring.flyway.ignore-migration-limits-check=true

# --- Server ---
server.http2.enabled=true
server.ssl.key-alias=localhost
server.address=0.0.0.0
server.ssl.key-store=${PATH_TO_KEYSTORE}
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
spring.aop.proxy-target-class=false
spring.mvc.hiddenmethod.filter.enabled=true


# ---  Mail ---
resend.api.key=${RESEND_API_KEY}

# --- Security ---
jwt.cookie-token-key=${JWT_COOKIE_TOKEN_KEY}
my.super.secret.key=${SUPER_SECRET_KEY}

# --- Hibernate 2nd Level Cache ---
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=jcache
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG
spring.jpa.properties.hibernate.javax.cache.missing_cache_strategy=create