spring.application.name=fitness-app

## Database Configuration
##spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_app?sessionTimezone=Europe/Kyiv
##spring.datasource.username=myuser
##spring.datasource.password=mypassword
##spring.datasource.driver-class-name=org.postgresql.Driver
#
#
##Server Configuration
#server.port=8080
#server.address=0.0.0.0
#
##Security Configuration
#jwt.cookie-token-key='{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'

spring.datasource.url=jdbc:h2:mem:fitness_test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.flyway.enabled=true
spring.flyway.schemas=fitness_app

# --- Server ---
server.http2.enabled=true
server.ssl.key-alias=localhost
server.address=0.0.0.0
server.ssl.key-store=${PATH_TO_KEYSTORE}
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
spring.aop.proxy-target-class=false
spring.mvc.hiddenmethod.filter.enabled=true

# ---  Mail ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- Security ---
jwt.cookie-token-key=${JWT_COOKIE_TOKEN_KEY}
my.super.secret.key=${SUPER_SECRET_KEY}

# --- Hibernate 2nd Level Cache ---
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=jcache
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG
spring.jpa.properties.hibernate.javax.cache.missing_cache_strategy=create