spring.application.name=fitness-app

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_app?sessionTimezone=Europe/Kyiv
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true


#Server Configuration
server.port=8080
server.address=0.0.0.0

#Security Configuration
jwt.cookie-token-key=