INSERT INTO fitness_app.exercise_definition (exercise_def_id, name)
VALUES (1, 'Barbell Bench Press'),
       (2, 'Barbell Squat'),
       (3, 'Deadlift'),
       (4, 'Overhead Press'),
       (5, 'Pull Up'),
       (6, 'Dumbbell Row'),
       (7, 'Barbell Row'),
       (8, 'Dumbbell Bench Press'),
       (9, 'Incline Bench Press'),
       (10, 'Leg Press'),
       (11, 'Lat Pulldown'),
       (12, 'Seated Cable Row'),
       (13, 'Face Pull'),
       (14, 'Dumbbell Curl'),
       (15, 'Hammer Curl'),
       (16, 'Tricep Rope Pushdown'),
       (17, 'Skullcrushers'),
       (18, 'Lateral Raise'),
       (19, 'Front Raise'),
       (20, 'Leg Extension'),
       (21, 'Leg Curl'),
       (22, 'Calf Raise'),
       (23, 'Lunges'),
       (24, 'Bulgarian Split Squat'),
       (25, 'Romanian Deadlift'),
       (26, 'Hip Thrust'),
       (27, 'Plank'),
       (28, 'Russian Twist'),
       (29, 'Hanging Leg Raise'),
       (30, 'Ab Wheel Rollout'),
       (31, 'Dips'),
       (32, 'Push Up'),
       (33, 'Mountain Climbers'),
       (34, 'Burpees'),
       (35, 'Kettlebell Swing'),
       (36, 'Box Jump'),
       (37, 'Cable Fly'),
       (38, 'Pec Deck Machine'),
       (39, 'T-Bar Row'),
       (40, 'Chin Up'),
       (41, 'Preacher Curl'),
       (42, 'Overhead Tricep Extension'),
       (43, 'Reverse Fly'),
       (44, 'Shrugs'),
       (45, 'Farmers Walk'),
       (46, 'Hack Squat'),
       (47, 'Good Morning'),
       (48, 'Sumo Deadlift'),
       (49, 'Clean and Jerk'),
       (50, 'Snatch');