INSERT INTO fitness_app.exercise_definition (exercise_def_id, name)
VALUES (1, 'Barbell Bench Press'),
       (2, 'Dumbbell Bench Press'),
       (3, 'Incline Barbell Bench Press'),
       (4, 'Barbell Squat'),
       (5, 'Leg Press'),
       (6, 'Leg Extension'),
       (7, 'Leg Curl'),
       (8, 'Deadlift'),
       (9, 'Romanian Deadlift'),
       (10, 'Pull Up'),
       (11, 'Lat Pulldown'),
       (12, 'Seated Cable Row'),
       (13, 'Barbell Row'),
       (14, 'Overhead Press'),
       (15, 'Lateral Raise'),
       (16, 'Cable Fly'),
       (17, 'Barbell Curl'),
       (18, 'Hammer Curl'),
       (19, 'Tricep Pushdown'),
       (20, 'Lying Tricep Extension'),
       (21, 'Dips'),
       (22, 'Plank'),
       (23, 'Crunches'),
       (24, 'Dumbbell Lunges'),
       (25, 'Hyperextension');